{
  "openapi": "3.0.0",
  "info": {
    "title": "Mytaskapp",
    "description": "The API",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://virtserver.swaggerhub.com/FIRLYDANISYIFANAPUTR/API/1.0.0",
      "description": "SwaggerHub API"
    }
  ],
  "paths": {
    "/login": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Login to system",
        "description": "Endpoint login user to the web-application",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/users"
              },
              "examples": {
                "example1": {
                  "summary": "Example login user id 1",
                  "value": {
                    "email": "popol@gmail.com",
                    "password": "12345"
                  }
                },
                "example2": {
                  "summary": "Example login user id 2",
                  "value": {
                    "email": "tigreal@gmail.com",
                    "password": "12345"
                  }
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful login",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_200"
                },
                "examples": {
                  "Example login user id 1": {
                    "value": {
                      "code": 200,
                      "message": "Successful login",
                      "data": {
                        "user_id": 1,
                        "email": "popol@gmail.com",
                        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBldGVyemFsYWlAZ21haWwuY29tIiwicGFzc3dvcmQiOiJAU2VjcmV0MTIzIn0.BZq48TAx5wci2LH48KW5geslrGR2ybr0-5Wol-HyDkI"
                      }
                    }
                  },
                  "Example login user id 2": {
                    "value": {
                      "code": 200,
                      "message": "Successful login",
                      "data": {
                        "user_id": 2,
                        "email": "tigreal@gmail.com",
                        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBldGVyemFsYWlAZ21haWwuY29tIiwicGFzc3dvcmQiOiJAU2VjcmV0MTIzIn0.BZq48TAx5wci2LH48KW5geslrGR2ybr0-5Wol-HyDkI"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_400"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_500"
                }
              }
            }
          }
        }
      }
    },
    "/users": {
      "post": {
        "tags": [
          "Users"
        ],
        "summary": "Create a new user",
        "description": "Endpoint create new user to the web",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/users"
              },
              "example": {
                "name": "Popol Kupa",
                "email": "popol@gmail.com",
                "password": "12345",
                "phone_number": "08979493169"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_201"
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_400_1"
                }
              }
            }
          },
          "401": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_401"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_500"
                }
              }
            }
          }
        }
      }
    },
    "/users/:{user_id}": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Get user profile",
        "description": "Get user information by their ID",
        "parameters": [
          {
            "name": "user_id",
            "in": "path",
            "description": "User ID",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success get spesific user data",
            "content": {
              "application/json": {
                "example": {
                  "code": 200,
                  "message": "Successful Operation",
                  "data": {
                    "user_id": 1,
                    "name": "Popol Kupa",
                    "email": "popol@gmail.com",
                    "phone_number": "08979493169",
                    "created_at": "2023/03/07"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_404"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_500"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      },
      "put": {
        "tags": [
          "Users"
        ],
        "summary": "Update user profile",
        "description": "Update user information by their ID",
        "parameters": [
          {
            "name": "user_id",
            "in": "path",
            "description": "User ID",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "$ref": "#/components/schemas/users_user_id_body"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "User information updated successfully",
            "content": {
              "application/json": {
                "examples": {
                  "example update 1": {
                    "summary": "Example update user id 1",
                    "value": {
                      "code": 200,
                      "message": "Successful Operation",
                      "data": {
                        "name": "Popol",
                        "email": "popol@gmail.com",
                        "phone_number": "08979493169",
                        "created_at": "2023/03/07",
                        "updated_at": "2023/04/07"
                      }
                    }
                  },
                  "example update 2": {
                    "summary": "Example update user id 2",
                    "value": {
                      "code": 200,
                      "message": "Successful Operation",
                      "data": {
                        "username": "tigreal",
                        "email": "tigreal@gmail.com",
                        "phone_number": "08736236236",
                        "created_at": "2023/03/07",
                        "updated_at": "2023/04/07"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_400_1"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_404"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_500"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      },
      "delete": {
        "tags": [
          "Users"
        ],
        "summary": "Delete user account",
        "description": "Deactive user information by their ID",
        "parameters": [
          {
            "name": "user_id",
            "in": "path",
            "description": "User ID",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User data deleted successfully",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_200_1"
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_400_1"
                }
              }
            }
          },
          "401": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_401"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_500"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/projects": {
      "get": {
        "tags": [
          "Projects"
        ],
        "summary": "Get list projects",
        "description": "Get list projects",
        "responses": {
          "200": {
            "description": "Success get specific project data",
            "content": {
              "application/json": {
                "example": {
                  "code": 200,
                  "message": "Successful Operation",
                  "data": {
                    "title": "Project My Task App",
                    "description": "My Tas App merupakan aplikasi yang digunakan untuk management task pengguna",
                    "user_id": 1,
                    "tasks": [
                      {
                        "project_id": 1,
                        "task_id": 1,
                        "title": "membuat crud user",
                        "completion_status": "complete"
                      },
                      {
                        "project_id": 1,
                        "task_id": 2,
                        "title": "membuat crud project",
                        "completion_status": "not complete"
                      }
                    ]
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_404"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_500"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      },
      "post": {
        "tags": [
          "Projects"
        ],
        "summary": "Register new project",
        "description": "Endpoint register new project to the web-application",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/projects"
              },
              "example": {
                "title": "Project My Task App",
                "description": "My Tas App merupakan aplikasi yang digunakan untuk management task pengguna."
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_201_1"
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_400_1"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_404"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_500"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/projects/:{project_id}": {
      "get": {
        "tags": [
          "Projects"
        ],
        "summary": "Get project by project_id",
        "description": "Get specific project by project_id",
        "parameters": [
          {
            "name": "project_id",
            "in": "path",
            "description": "Project ID",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success get specific project data",
            "content": {
              "application/json": {
                "example": {
                  "code": 200,
                  "message": "Successful Operation",
                  "data": {
                    "title": "Project My Task App",
                    "description": "My Tas App merupakan aplikasi yang digunakan untuk management task pengguna",
                    "user_id": 1,
                    "tasks": [
                      {
                        "project_id": 1,
                        "task_id": 1,
                        "title": "membuat crud user",
                        "completion_status": "complete"
                      },
                      {
                        "project_id": 1,
                        "task_id": 2,
                        "title": "membuat crud project",
                        "completion_status": "not complete"
                      }
                    ]
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_404"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_500"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      },
      "put": {
        "tags": [
          "Projects"
        ],
        "summary": "Update project by project_id",
        "description": "Update specific project by project_id",
        "parameters": [
          {
            "name": "project_id",
            "in": "path",
            "description": "Project ID",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/projects_project_id_body"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Project information updated successfully",
            "content": {
              "application/json": {
                "example": {
                  "code": 200,
                  "message": "Successful Operation",
                  "data": {
                    "project_id": 1,
                    "title": "Project My Task App",
                    "description": "My Tas App merupakan aplikasi yang digunakan untuk management task pengguna.",
                    "user_id": 1
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_400_1"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_404"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_500"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      },
      "delete": {
        "tags": [
          "Projects"
        ],
        "summary": "Delete project by project_id",
        "description": "Delete specific project by project_id",
        "parameters": [
          {
            "name": "project_id",
            "in": "path",
            "description": "Project ID",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Project data deleted successfully",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_200_2"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_404"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_500"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/tasks": {
      "get": {
        "tags": [
          "Tasks"
        ],
        "summary": "Get list tasks",
        "description": "Get list tasks",
        "responses": {
          "200": {
            "description": "Success get specific task data",
            "content": {
              "application/json": {
                "example": {
                  "code": 200,
                  "message": "Successful Operation",
                  "data": {
                    "title": "Project My Task App",
                    "description": "My Tas App merupakan aplikasi yang digunakan untuk management task pengguna",
                    "user_id": 1,
                    "tasks": [
                      {
                        "task_id": 1,
                        "title": "membuat crud user",
                        "project_id": 1,
                        "completion_status": "not complete",
                        "created_at": "2023/03/07"
                      }
                    ]
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_404"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_500"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      },
      "post": {
        "tags": [
          "Tasks"
        ],
        "summary": "Register new task",
        "description": "Endpoint register new task to the web-application",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/tasks"
              },
              "example": {
                "title": "membuat crud user",
                "project_id": 1
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_201_2"
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_400_1"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_404"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_500"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/tasks/:{task_id}": {
      "get": {
        "tags": [
          "Tasks"
        ],
        "summary": "Get task by task_id",
        "description": "Get specific task by task_id",
        "parameters": [
          {
            "name": "task_id",
            "in": "path",
            "description": "Task ID",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success get specific task data",
            "content": {
              "application/json": {
                "example": {
                  "code": 200,
                  "message": "Successful Operation",
                  "data": {
                    "title": "Project My Task App",
                    "description": "My Tas App merupakan aplikasi yang digunakan untuk management task pengguna",
                    "user_id": 1,
                    "tasks": [
                      {
                        "task_id": 1,
                        "title": "membuat crud user",
                        "project_id": 1,
                        "completion_status": "not complete",
                        "created_at": "2023/03/07"
                      }
                    ]
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_404"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_500"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      },
      "put": {
        "tags": [
          "Tasks"
        ],
        "summary": "Update task by task_id",
        "description": "Update specific task by task_id",
        "parameters": [
          {
            "name": "task_id",
            "in": "path",
            "description": "Task ID",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/tasks_task_id_body"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Project information updated successfully",
            "content": {
              "application/json": {
                "example": {
                  "code": 200,
                  "message": "Successful Operation",
                  "data": [
                    {
                      "project_id": 1,
                      "title": "membuat crud user",
                      "completion_status": "complete"
                    }
                  ]
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_400_1"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_404"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_500"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      },
      "delete": {
        "tags": [
          "Tasks"
        ],
        "summary": "Delete task by task_id",
        "description": "Delete specific task by task_id",
        "parameters": [
          {
            "name": "task_id",
            "in": "path",
            "description": "Task ID",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Project data deleted successfully",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_200_3"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_404"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_500"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "users": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid"
          },
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string",
            "format": "email"
          },
          "password": {
            "type": "string"
          },
          "phone_number": {
            "type": "string"
          },
          "created_at": {
            "type": "string",
            "format": "date-time"
          },
          "updated_at": {
            "type": "string",
            "format": "date-time"
          },
          "deleted_at": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "projects": {
        "type": "object",
        "properties": {
          "project_id": {
            "type": "string",
            "format": "uuid"
          },
          "title": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "created_at": {
            "type": "string",
            "format": "date-time"
          },
          "updated_at": {
            "type": "string",
            "format": "date-time"
          },
          "deleted_at": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "tasks": {
        "type": "object",
        "properties": {
          "task_id": {
            "type": "string",
            "format": "uuid"
          },
          "title": {
            "type": "string"
          },
          "project_id": {
            "type": "string"
          },
          "completion_status": {
            "type": "string"
          },
          "created_at": {
            "type": "string",
            "format": "date-time"
          },
          "updated_at": {
            "type": "string",
            "format": "date-time"
          },
          "deleted_at": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "inline_response_200": {
        "type": "object",
        "properties": {
          "code": {
            "type": "integer"
          },
          "message": {
            "type": "string"
          },
          "token": {
            "type": "string"
          }
        },
        "example": {
          "code": 200,
          "message": "Successful login",
          "data": {
            "user_id": 1,
            "email": "popol@gmail.com",
            "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBldGVyemFsYWlAZ21haWwuY29tIiwicGFzc3dvcmQiOiJAU2VjcmV0MTIzIn0.BZq48TAx5wci2LH48KW5geslrGR2ybr0-5Wol-HyDkI"
          }
        }
      },
      "inline_response_400": {
        "type": "object",
        "properties": {
          "code": {
            "type": "integer",
            "example": 400
          },
          "message": {
            "type": "string",
            "example": "Bad request, Incorrect email or password"
          }
        }
      },
      "inline_response_500": {
        "type": "object",
        "properties": {
          "code": {
            "type": "integer",
            "example": 500
          },
          "message": {
            "type": "string",
            "example": "Internal server error"
          }
        }
      },
      "inline_response_201": {
        "type": "object",
        "properties": {
          "code": {
            "type": "integer"
          },
          "message": {
            "type": "string"
          }
        },
        "example": {
          "code": 200,
          "message": "Successful created an account",
          "data": {
            "id": 1,
            "name": "Popol Kupa",
            "email": "popol@gmail.com"
          }
        }
      },
      "inline_response_400_1": {
        "type": "object",
        "properties": {
          "code": {
            "type": "integer",
            "example": 400
          },
          "message": {
            "type": "string",
            "example": "Bad request"
          }
        }
      },
      "inline_response_401": {
        "type": "object",
        "properties": {
          "code": {
            "type": "integer",
            "example": 401
          },
          "message": {
            "type": "string",
            "example": "Unauthorized access."
          }
        }
      },
      "inline_response_404": {
        "type": "object",
        "properties": {
          "code": {
            "type": "integer",
            "example": 404
          },
          "message": {
            "type": "string",
            "example": "The requested resource was not found"
          }
        }
      },
      "users_user_id_body": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string",
            "format": "email"
          },
          "password": {
            "type": "string"
          },
          "phone_number": {
            "type": "string"
          }
        }
      },
      "inline_response_200_1": {
        "type": "object",
        "properties": {
          "code": {
            "type": "integer",
            "example": 200
          },
          "message": {
            "type": "string",
            "example": "Success Delete Account"
          }
        }
      },
      "inline_response_201_1": {
        "type": "object",
        "properties": {
          "code": {
            "type": "integer"
          },
          "message": {
            "type": "string"
          }
        },
        "example": {
          "code": 200,
          "message": "Successful created new project",
          "data": {
            "title": "Project My Task App",
            "description": "My Tas App merupakan aplikasi yang digunakan untuk management task pengguna",
            "user_id": 1
          }
        }
      },
      "projects_project_id_body": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string"
          },
          "description": {
            "type": "string"
          }
        }
      },
      "inline_response_200_2": {
        "type": "object",
        "properties": {
          "code": {
            "type": "integer",
            "example": 200
          },
          "message": {
            "type": "string",
            "example": "Success Delete Project"
          }
        }
      },
      "inline_response_201_2": {
        "type": "object",
        "properties": {
          "code": {
            "type": "integer"
          },
          "message": {
            "type": "string"
          }
        },
        "example": {
          "code": 200,
          "message": "Successful created new project",
          "data": {
            "task_id": 1,
            "title": "membuat crud user",
            "project_id": 1,
            "completion_status": "not complete"
          }
        }
      },
      "tasks_task_id_body": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string"
          },
          "description": {
            "type": "string"
          }
        }
      },
      "inline_response_200_3": {
        "type": "object",
        "properties": {
          "code": {
            "type": "integer",
            "example": 200
          },
          "message": {
            "type": "string",
            "example": "Success Delete task"
          }
        }
      }
    },
    "responses": {
      "Response200": {
        "description": "Successful operation",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "code": {
                  "type": "integer",
                  "example": 200
                },
                "message": {
                  "type": "string",
                  "example": "Successful operation"
                }
              }
            }
          }
        }
      },
      "Response201": {
        "description": "Successful operation",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "code": {
                  "type": "integer",
                  "example": 201
                },
                "message": {
                  "type": "string",
                  "example": "Successful operation"
                }
              }
            }
          }
        }
      },
      "Response201CreateUser": {
        "description": "Successful operation",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/inline_response_201"
            }
          }
        }
      },
      "Response201CreateProject": {
        "description": "Successful operation",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/inline_response_201_1"
            }
          }
        }
      },
      "Response201CreateTask": {
        "description": "Successful operation",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/inline_response_201_2"
            }
          }
        }
      },
      "Response200Login": {
        "description": "Successful login",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/inline_response_200"
            },
            "examples": {
              "Example login user id 1": {
                "value": {
                  "code": 200,
                  "message": "Successful login",
                  "data": {
                    "user_id": 1,
                    "email": "popol@gmail.com",
                    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBldGVyemFsYWlAZ21haWwuY29tIiwicGFzc3dvcmQiOiJAU2VjcmV0MTIzIn0.BZq48TAx5wci2LH48KW5geslrGR2ybr0-5Wol-HyDkI"
                  }
                }
              },
              "Example login user id 2": {
                "value": {
                  "code": 200,
                  "message": "Successful login",
                  "data": {
                    "user_id": 2,
                    "email": "tigreal@gmail.com",
                    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBldGVyemFsYWlAZ21haWwuY29tIiwicGFzc3dvcmQiOiJAU2VjcmV0MTIzIn0.BZq48TAx5wci2LH48KW5geslrGR2ybr0-5Wol-HyDkI"
                  }
                }
              }
            }
          }
        }
      },
      "Response200GetListProjects": {
        "description": "Success get list projects",
        "content": {
          "application/json": {
            "example": {
              "code": 200,
              "message": "Successful Operation",
              "data": [
                {
                  "title": "Project My Task App",
                  "description": "My Tas App merupakan aplikasi yang digunakan untuk management task pengguna",
                  "user_id": 1,
                  "created_at": "2023/03/07"
                },
                {
                  "title": "Project Taman",
                  "description": "Memperindah taman dengan menanam beberapa jenis bunga",
                  "user_id": 1,
                  "created_at": "2023/03/07"
                }
              ]
            }
          }
        }
      },
      "Response200GetListTasks": {
        "description": "Success get list tasks",
        "content": {
          "application/json": {
            "example": {
              "code": 200,
              "message": "Successful Operation",
              "data": [
                {
                  "task_id": 1,
                  "title": "membuat crud user",
                  "project_id": 1,
                  "completion_status": "not complete",
                  "created_at": "2023/03/07"
                },
                {
                  "task_id": 2,
                  "title": "menanam bunga mawar",
                  "project_id": 1,
                  "completion_status": "not complete",
                  "created_at": "2023/03/07"
                }
              ]
            }
          }
        }
      },
      "Response200GetUserProfile": {
        "description": "Success get spesific user data",
        "content": {
          "application/json": {
            "example": {
              "code": 200,
              "message": "Successful Operation",
              "data": {
                "user_id": 1,
                "name": "Popol Kupa",
                "email": "popol@gmail.com",
                "phone_number": "08979493169",
                "created_at": "2023/03/07"
              }
            }
          }
        }
      },
      "Response200GetProject": {
        "description": "Success get specific project data",
        "content": {
          "application/json": {
            "example": {
              "code": 200,
              "message": "Successful Operation",
              "data": {
                "title": "Project My Task App",
                "description": "My Tas App merupakan aplikasi yang digunakan untuk management task pengguna",
                "user_id": 1,
                "tasks": [
                  {
                    "project_id": 1,
                    "task_id": 1,
                    "title": "membuat crud user",
                    "completion_status": "complete"
                  },
                  {
                    "project_id": 1,
                    "task_id": 2,
                    "title": "membuat crud project",
                    "completion_status": "not complete"
                  }
                ]
              }
            }
          }
        }
      },
      "Response200GetTask": {
        "description": "Success get specific task data",
        "content": {
          "application/json": {
            "example": {
              "code": 200,
              "message": "Successful Operation",
              "data": {
                "title": "Project My Task App",
                "description": "My Tas App merupakan aplikasi yang digunakan untuk management task pengguna",
                "user_id": 1,
                "tasks": [
                  {
                    "task_id": 1,
                    "title": "membuat crud user",
                    "project_id": 1,
                    "completion_status": "not complete",
                    "created_at": "2023/03/07"
                  }
                ]
              }
            }
          }
        }
      },
      "Response200UpdateUser": {
        "description": "User information updated successfully",
        "content": {
          "application/json": {
            "examples": {
              "example update 1": {
                "summary": "Example update user id 1",
                "value": {
                  "code": 200,
                  "message": "Successful Operation",
                  "data": {
                    "name": "Popol",
                    "email": "popol@gmail.com",
                    "phone_number": "08979493169",
                    "created_at": "2023/03/07",
                    "updated_at": "2023/04/07"
                  }
                }
              },
              "example update 2": {
                "summary": "Example update user id 2",
                "value": {
                  "code": 200,
                  "message": "Successful Operation",
                  "data": {
                    "username": "tigreal",
                    "email": "tigreal@gmail.com",
                    "phone_number": "08736236236",
                    "created_at": "2023/03/07",
                    "updated_at": "2023/04/07"
                  }
                }
              }
            }
          }
        }
      },
      "Response200UpdateProject": {
        "description": "Project information updated successfully",
        "content": {
          "application/json": {
            "example": {
              "code": 200,
              "message": "Successful Operation",
              "data": {
                "project_id": 1,
                "title": "Project My Task App",
                "description": "My Tas App merupakan aplikasi yang digunakan untuk management task pengguna.",
                "user_id": 1
              }
            }
          }
        }
      },
      "Response200UpdateTask": {
        "description": "Project information updated successfully",
        "content": {
          "application/json": {
            "example": {
              "code": 200,
              "message": "Successful Operation",
              "data": [
                {
                  "project_id": 1,
                  "title": "membuat crud user",
                  "completion_status": "complete"
                }
              ]
            }
          }
        }
      },
      "Response200UserDelete": {
        "description": "User data deleted successfully",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/inline_response_200_1"
            }
          }
        }
      },
      "Response200ProjectDelete": {
        "description": "Project data deleted successfully",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/inline_response_200_2"
            }
          }
        }
      },
      "Response200TaskDelete": {
        "description": "Project data deleted successfully",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/inline_response_200_3"
            }
          }
        }
      },
      "Response400Login": {
        "description": "Bad request",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/inline_response_400"
            }
          }
        }
      },
      "Response400": {
        "description": "Bad request",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/inline_response_400_1"
            }
          }
        }
      },
      "Response401Unauthorized": {
        "description": "Bad request",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/inline_response_401"
            }
          }
        }
      },
      "Response404": {
        "description": "Not Found",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/inline_response_404"
            }
          }
        }
      },
      "Response500": {
        "description": "Internal server error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/inline_response_500"
            }
          }
        }
      }
    },
    "requestBodies": {
      "RequestLoginUser": {
        "content": {
          "multipart/form-data": {
            "schema": {
              "$ref": "#/components/schemas/users"
            }
          }
        },
        "required": true
      }
    },
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
